### ISSUE TITLE
401, Fix plz!

### ISSUE THREAD

**Issue by shelllshock** [SudoLite/MMProBumpBot#1]
<img width="1295" alt="Снимок экрана 2024-07-08 в 18 36 10" src="https://github.com/SudoLite/MMProBumpBot/assets/172393950/e2d12213-d24e-4cbf-8de8-6094ebf459bf">

**Comment by HoyT6yK** [comment]
Скорее всего эта ошибка на твоей стороне. Попробуй сменить/использовать прокси или пересоздать сессию.

**Comment by SudoLite** [comment]
Fixed
