### ISSUE TITLE
405

### ISSUE THREAD

**Issue by laggedv1** [SudoLite/MMProBumpBot#2]
Doesnt work any fix 
![imagen](https://github.com/SudoLite/MMProBumpBot/assets/174215942/2418ae89-4ee1-4312-8b33-6d682e4595b0)

**Comment by laggedv1** [comment]
Imo your doing some api call that triggers the system to block me, i dont have that many accounts to be blocked

**Comment by shelllshock** [comment]
![22](https://github.com/SudoLite/MMProBumpBot/assets/172393950/fb92d03e-bb69-4d9d-8e51-28fe56055309)
Снова сломался :(

**Comment by laggedv1** [comment]
working using proxy , lets see how long this ip survives

**Comment by SudoLite** [comment]
Fixed

**Comment by laggedv1** [comment]
> Fixed

Goat ngl
